const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cities=[['Tokyo, Japan',35.6762,139.6503],['Karachi, Pakistan',24.8607,67.0011],['Cairo, Egypt',30.0444,31.2357],['San Francisco, USA',37.7749,-122.4194],['Istanbul, Türkiye',41.0082,28.9784],['London, United Kingdom',51.5072,-.1276]];
const satelliteStyle={version:8,sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'© Esri'}},layers:[{id:'satellite',type:'raster',source:'satellite'}]};
const streetStyle={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
let events=[],markers=[],streetMode=false,playing=false;
const hasMap=Boolean(window.maplibregl);
const map=hasMap?new maplibregl.Map({container:'map',style:satelliteStyle,center:[45,20],zoom:2.15,minZoom:1.3,maxZoom:17,attributionControl:true}):{flyTo(){},zoomIn(){},zoomOut(){},resetNorth(){},on(){},once(){},setStyle(){}};
if(hasMap)map.addControl(new maplibregl.NavigationControl({showCompass:false}));
if(!hasMap){$('#map').innerHTML='<div class="map-grid"></div><div class="continent c1"></div><div class="continent c2"></div><div class="continent c3"></div><div class="cloud cloud1"></div><div class="cloud cloud2"></div><div class="scan"></div><div class="map-fallback-note">Map connection unavailable<br><span>Live events continue below</span></div>'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2600)}
function openEvent(e){$('#event-place').textContent=e.place;$('#event-mag').textContent='M '+e.mag.toFixed(1);$('#event-depth').textContent=Math.round(e.depth)+' km';$('#event-coords').textContent=`${e.lat.toFixed(2)}°, ${e.lon.toFixed(2)}°`;$('#event-time').textContent=new Date(e.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#event-panel').classList.add('show');map.flyTo({center:[e.lon,e.lat],zoom:5.2,duration:1400})}
function addMarker(e){if(!hasMap)return;const el=document.createElement('button');el.className='marker '+(e.mag>=5?'mag5':'');el.dataset.place=e.place;el.innerHTML='<i></i>';el.onclick=()=>openEvent(e);markers.push({type:'earthquakes',el,instance:new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([e.lon,e.lat]).addTo(map)})}
function addISS(){if(!hasMap)return;const el=document.createElement('button');el.className='marker iss';el.dataset.place='ISS · 408 km above Earth';el.innerHTML='<i></i>';el.onclick=()=>toast('ISS is currently passing over the Arabian Sea');markers.push({type:'iss',el,instance:new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([61,25]).addTo(map)})}
function renderHeadlines(){const list=$('#headline-list');const top=[...events].sort((a,b)=>b.mag-a.mag).slice(0,3);list.innerHTML='';top.forEach((e,i)=>{const button=document.createElement('button');button.className='headline';button.innerHTML=`<span class="headline-index">0${i+1}</span><span><small>SEISMIC · M ${e.mag.toFixed(1)}</small><b>${e.place.replace(/^\d+ km [A-Z]+ of /,'')}</b></span>`;button.onclick=()=>openEvent(e);list.append(button);if(hasMap){const el=document.createElement('button');el.className='headline-marker';el.innerHTML=`<i></i><span>M ${e.mag.toFixed(1)} · ${e.place.replace(/^\d+ km [A-Z]+ of /,'')}</span>`;el.onclick=()=>openEvent(e);markers.push({type:'headline',el,instance:new maplibregl.Marker({element:el,anchor:'bottom-left',offset:[5,-24]}).setLngLat([e.lon,e.lat]).addTo(map)})}})}
function feedItem(e){const d=document.createElement('div');d.className='feed-item';d.innerHTML=`<span class="feed-icon quake">⌁</span><div><small>NOW · SEISMIC</small><b>M ${e.mag.toFixed(1)} · ${e.place.replace(/^\d+ km [A-Z]+ of /,'')}</b><p>${Math.round(e.depth)} km deep · ${new Date(e.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} UTC</p></div>`;d.onclick=()=>openEvent(e);return d}
async function loadQuakes(){try{const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson'),j=await r.json();events=j.features.filter(x=>x.properties.mag>=2.5).slice(0,18).map(x=>({mag:x.properties.mag,place:x.properties.place||'Unknown location',time:x.properties.time,lon:x.geometry.coordinates[0],lat:x.geometry.coordinates[1],depth:x.geometry.coordinates[2]}));$('#quake-count').textContent=j.metadata.count.toLocaleString()}catch{events=[{mag:5.2,place:'132 km E of Hachijo-jima, Japan',time:Date.now(),lat:33.2,lon:141.9,depth:28},{mag:4.7,place:'Pacific Ocean',time:Date.now()-120000,lat:12,lon:-120,depth:14}];$('#quake-count').textContent='218';toast('Live feed unavailable — showing cached activity')}events.forEach(addMarker);const f=$('#feed-list');f.innerHTML='';events.slice(0,5).forEach(e=>f.append(feedItem(e)));addISS();renderHeadlines()}
function flyTo(name,lat,lon){map.flyTo({center:[lon,lat],zoom:5.3,essential:true,duration:1800});$('#view-name').textContent=name;$('#view-coords').textContent=`${lat.toFixed(4)}° ${lat>=0?'N':'S'}, ${lon.toFixed(4)}° ${lon>=0?'E':'W'}`;toast(`Flying to ${name}`)}
$('#search').oninput=e=>{const q=e.target.value.toLowerCase(),r=$('#search-results');if(!q)return r.classList.remove('show');const found=cities.filter(c=>c[0].toLowerCase().includes(q)).slice(0,4);r.innerHTML=found.map((c,i)=>`<button data-i="${i}">⌖ &nbsp; ${c[0]}</button>`).join('')||'<button>No matching destinations</button>';r.classList.add('show');$$('#search-results button[data-i]').forEach(b=>b.onclick=()=>{const c=found[b.dataset.i];flyTo(...c);r.classList.remove('show');$('#search').value=c[0]})};
$('#map-mode').onclick=()=>{if(!hasMap)return toast('Map renderer is unavailable while offline');streetMode=!streetMode;markers.forEach(m=>m.instance.remove());markers=[];map.setStyle(streetMode?streetStyle:satelliteStyle);$('#map-mode').textContent=streetMode?'MAP':'SATELLITE';map.once('style.load',()=>{events.forEach(addMarker);addISS();renderHeadlines()})};
$('#close-panel').onclick=()=>$('#event-panel').classList.remove('show');$('#collapse-sidebar').onclick=()=>$('#sidebar').classList.toggle('open');$('#layers-all').onclick=()=>$$('.layers input').forEach(x=>x.checked=true);$('#layers').onchange=e=>{const type=e.target.dataset.layer;if(type==='earthquakes'||type==='iss')markers.filter(m=>m.type===type).forEach(m=>m.el.style.display=e.target.checked?'block':'none');toast(`${e.target.parentElement.innerText.trim()} ${e.target.checked?'enabled':'hidden'}`)};
$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'❚❚':'▶';toast(playing?'Replaying the last 24 hours':'Replay paused')};$('#timeline-range').oninput=e=>{$('#timeline-label').textContent=e.target.value==100?'LIVE · NOW':`${Math.round((100-e.target.value)*.24)}H AGO`;markers.forEach((m,i)=>m.el.style.opacity=Math.max(.18,1-(100-e.target.value)/130-i*.018))};$('#plus').onclick=()=>map.zoomIn();$('#minus').onclick=()=>map.zoomOut();$('#compass').onclick=()=>{map.resetNorth();toast('North aligned')};$('#locate').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>flyTo('Your location',p.coords.latitude,p.coords.longitude),()=>toast('Location access was not granted')):toast('Geolocation is not available');$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(`GeoPulse alert: ${$('#event-mag').textContent} — ${$('#event-place').textContent}`);toast('Event summary copied')}catch{toast('Share summary ready')}};$('#notify').onclick=()=>toast('3 new Earth alerts');$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(b.dataset.view==='near'?'Enable location to see nearby conditions':`${b.textContent.trim()} opened`)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){$('#event-panel').classList.remove('show');$('#search-results').classList.remove('show')}if(e.key.toLowerCase()==='l')$('#sidebar').classList.toggle('open')});
if(hasMap){map.on('load',loadQuakes);map.once('error',()=>{if(!streetMode){streetMode=true;map.setStyle(streetStyle);$('#map-mode').textContent='MAP';toast('Satellite imagery was unavailable — switched to map view')}})}else loadQuakes();const steps=['Connecting to Earth...','Loading satellites...','Loading weather systems...','Loading earthquake feed...','Synchronization complete'];let i=0;const boot=setInterval(()=>{i++;if(i<steps.length)$('#boot-text').textContent=steps[i];else{clearInterval(boot);setTimeout(()=>$('#intro').classList.add('hide'),500)}},650);
