const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cities=[['Tokyo, Japan',35.6762,139.6503],['Karachi, Pakistan',24.8607,67.0011],['Cairo, Egypt',30.0444,31.2357],['San Francisco, USA',37.7749,-122.4194],['Istanbul, Türkiye',41.0082,28.9784],['London, United Kingdom',51.5072,-.1276]];
let events=[],playing=false,zoom=1;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2600)}
function coordsToScreen(lat,lon){return {x:50+(lon/360)*73,y:53-(lat/180)*57}}
function addMarker(e,i){const p=coordsToScreen(e.lat,e.lon),m=document.createElement('button');m.className='marker '+(e.mag>=5?'mag5':'');m.style.left=p.x+'%';m.style.top=p.y+'%';m.dataset.place=e.place;m.setAttribute('aria-label',`Earthquake ${e.mag} at ${e.place}`);m.innerHTML='<i></i>';m.onclick=()=>openEvent(e);$('#markers').append(m)}
function openEvent(e){$('#event-place').textContent=e.place;$('#event-mag').textContent='M '+e.mag.toFixed(1);$('#event-depth').textContent=Math.round(e.depth)+' km';$('#event-coords').textContent=`${e.lat.toFixed(2)}°, ${e.lon.toFixed(2)}°`;$('#event-time').textContent=new Date(e.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#event-panel').classList.add('show');$('#view-name').textContent=e.place.split(' of ').pop();$('#view-coords').textContent=`${e.lat.toFixed(4)}° ${e.lat>=0?'N':'S'}, ${e.lon.toFixed(4)}° ${e.lon>=0?'E':'W'}`}
function feedItem(e){const d=document.createElement('div');d.className='feed-item';d.innerHTML=`<span class="feed-icon quake">⌁</span><div><small>NOW · SEISMIC</small><b>M ${e.mag.toFixed(1)} · ${e.place.replace(/^\d+ km [A-Z]+ of /,'')}</b><p>${Math.round(e.depth)} km deep · ${new Date(e.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} UTC</p></div>`;d.onclick=()=>openEvent(e);return d}
async function loadQuakes(){try{const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson');const j=await r.json();events=j.features.filter(x=>x.properties.mag>=2.5).slice(0,18).map(x=>({mag:x.properties.mag,place:x.properties.place||'Unknown location',time:x.properties.time,lon:x.geometry.coordinates[0],lat:x.geometry.coordinates[1],depth:x.geometry.coordinates[2]}));$('#quake-count').textContent=j.metadata.count.toLocaleString();$('#markers').innerHTML='';events.forEach(addMarker);const feed=$('#feed-list');feed.innerHTML='';events.slice(0,5).forEach(e=>feed.append(feedItem(e)))}catch{events=[{mag:5.2,place:'132 km E of Hachijo-jima, Japan',time:Date.now(),lat:33.2,lon:141.9,depth:28},{mag:4.7,place:'Pacific Ocean',time:Date.now()-120000,lat:12,lon:-120,depth:14}];events.forEach(addMarker);$('#quake-count').textContent='218';const f=$('#feed-list');f.innerHTML='';events.forEach(e=>f.append(feedItem(e)));toast('Live feed unavailable — showing cached activity') }}
function addISS(){const m=document.createElement('button');m.className='marker iss';m.style.left='59%';m.style.top='37%';m.dataset.place='ISS · 408 km above Earth';m.innerHTML='<i></i>';m.onclick=()=>toast('ISS is currently passing over the Arabian Sea');$('#markers').append(m)}
function flyTo(name,lat,lon){$('#map').animate([{transform:'scale(1)'},{transform:'scale(1.09)'},{transform:'scale(1)'}],{duration:900,easing:'cubic-bezier(.2,.8,.2,1)'});$('#view-name').textContent=name;$('#view-coords').textContent=`${lat.toFixed(4)}° ${lat>=0?'N':'S'}, ${lon.toFixed(4)}° ${lon>=0?'E':'W'}`;toast(`Flying to ${name}`)}
$('#search').oninput=e=>{const q=e.target.value.toLowerCase();const r=$('#search-results');if(!q){r.classList.remove('show');return}const found=cities.filter(c=>c[0].toLowerCase().includes(q)).slice(0,4);r.innerHTML=found.map((c,i)=>`<button data-i="${i}">⌖ &nbsp; ${c[0]}</button>`).join('')||'<button>No matching destinations</button>';r.classList.add('show');$$('#search-results button[data-i]').forEach(b=>b.onclick=()=>{const c=found[b.dataset.i];flyTo(...c);r.classList.remove('show');$('#search').value=c[0]})};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){$('#event-panel').classList.remove('show');$('#search-results').classList.remove('show')}if(e.key.toLowerCase()==='l')$('#sidebar').classList.toggle('open')});
$('#close-panel').onclick=()=>$('#event-panel').classList.remove('show');$('#collapse-sidebar').onclick=()=>$('#sidebar').classList.toggle('open');$('#layers-all').onclick=()=>$$('.layers input').forEach(x=>x.checked=true);$('#layers').onchange=e=>{const type=e.target.dataset.layer;if(type==='earthquakes')$$('.marker:not(.iss)').forEach(m=>m.style.display=e.target.checked?'block':'none');if(type==='iss')$('.marker.iss')&&( $('.marker.iss').style.display=e.target.checked?'block':'none');if(type==='clouds')$$('.cloud').forEach(x=>x.style.display=e.target.checked?'block':'none');toast(`${e.target.parentElement.innerText.trim()} ${e.target.checked?'enabled':'hidden'}`)};
$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'❚❚':'▶';toast(playing?'Replaying the last 24 hours':'Replay paused')};$('#timeline-range').oninput=e=>{$('#timeline-label').textContent=e.target.value==100?'LIVE · NOW':`${Math.round((100-e.target.value)*.24)}H AGO`;$$('.marker').forEach((m,i)=>m.style.opacity=Math.max(.18,1-(100-e.target.value)/130-i*.018))};$('#plus').onclick=()=>{zoom=Math.min(1.3,zoom+.08);$('#map').style.transform=`scale(${zoom})`};$('#minus').onclick=()=>{zoom=Math.max(.8,zoom-.08);$('#map').style.transform=`scale(${zoom})`};$('#compass').onclick=()=>{$('#map').style.transform='scale(1)';zoom=1;toast('North aligned')};$('#locate').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>flyTo('Your location',p.coords.latitude,p.coords.longitude),()=>toast('Location access was not granted')):toast('Geolocation is not available');$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(`GeoPulse alert: ${$('#event-mag').textContent} — ${$('#event-place').textContent}`);toast('Event summary copied to clipboard')}catch{toast('Share summary ready')}};$('#notify').onclick=()=>toast('3 new Earth alerts');$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(b.dataset.view==='near'?'Enable location to see nearby conditions':`${b.textContent.trim()} opened`)});
const steps=['Connecting to Earth...','Loading satellites...','Loading weather systems...','Loading earthquake feed...','Synchronization complete'];let i=0;const boot=setInterval(()=>{i++;if(i<steps.length)$('#boot-text').textContent=steps[i];else{clearInterval(boot);setTimeout(()=>$('#intro').classList.add('hide'),500)}},650);loadQuakes().then(addISS);
